name: Rails CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7.44
        env:
          MYSQL_ROOT_PASSWORD: password 
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0' 

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        gem install bundler
        bundle install

    - name: Setup database
      run: |
        sudo /etc/init.d/mysql start
        cp config/database.ci.yml config/database.yml
        bundle exec rails db:create db:schema:load RAILS_ENV=test

    - name: Run RSpec
      run: bundle exec rspec

    - name: Run RuboCop
      run: bundle exec rubocop
